name: Deploy RDS instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy CloudFormation template
      run: |
        aws cloudformation create-stack \
          --stack-name my-db-stack \
          --template-body file://cloudformation.yml \
          --parameters ParameterKey=VpcId,ParameterValue=vpc-12345678 \
          --capabilities CAPABILITY_NAMED_IAM
